name: ci

on:
  push:

jobs:

  tests:
    strategy:
      matrix:
        name: [unit]
    runs-on: ubuntu-latest
    name: test (${{ matrix.name }})
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0


      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run ${{ matrix.name }} tests
        run: make test

  builds:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    name: build (${{ matrix.os }})

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build
        run: make build
